from distutils.core import setup
setup(
    name='hub_dados',
    version='1.2.0',
    packages=['hub_dados'],
    url='https://github.com/amisampaio/hub_dados',
    license='Apache 2.0',
    author='Amilcar Sampaio',
    author_email='amilcar.sampaio@gmail.com',
    description='Hub de dados',
    install_requires=[
        'boto3',
        'pandas',
        'pyarrow',
        'requests',
        'python-dateutil',
        'pytz',
        'tqdm',
        'chardet',
        'google-cloud-storage',
        'google-cloud-bigquery',
        'db-dtypes',
    ],
    extras_require={
        'aws': ['boto3'],
        'gcp': ['google-cloud-storage', 'google-cloud-bigquery', 'db-dtypes'],
        'gitlab': ['python-gitlab'],
        'viz': ['seaborn', 'matplotlib'],
    },
)
